"""
agents/edit_detector.py
 
Runs FIRST on every intake turn before the intake agent.
 
Decides whether the user's message is:
  - A CORRECTION  → patch a specific field in the existing case log
  - NEW INFO      → pass through to intake agent for normal field extraction
  - CONTRADICTION → ask the user to confirm which version is correct
 
Reads : state["raw_query"], state["case_log"]
Writes: state["edit_detected"], state["edited_fields"], state["case_log"], state["answer"]
 
If edit_detected is True, the intake graph skips the intake agent for this turn
and routes directly to the response node so the corrected log is sent back to the UI.
"""
 
import os
import json
from dotenv import load_dotenv
 
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
 
from .agent_state import GraphState
from .models import CaseLog, CaseParties
 
load_dotenv()
 
_SYSTEM_PROMPT = """You are an edit detector for a legal case intake system.
 
The user has an existing case log that was built during an intake conversation.
Your job is to decide if the user's latest message is CORRECTING something in the log
or providing NEW information.
 
CORRECTION signals (user is fixing something already logged):
- "that's wrong", "not exactly", "I meant", "actually", "correction", "no I said"
- Contradicts a specific field already in the log
- Rephrases something already captured with a different meaning
 
NEW INFO signals (user is adding something not yet in the log):
- Mentions a detail not captured anywhere in the log
- Answers a question the intake agent asked
- Elaborates on something vague in the log
 
CONTRADICTION signals (genuinely unclear which version is true):
- User says two things that cannot both be true about the same field
 
You must respond ONLY in this JSON format, no markdown, no preamble:
{
  "edit_type": "correction" | "new_info" | "contradiction",
  "fields_affected": ["field_name", ...],
  "corrected_values": {
    "field_name": "new value as plain string"
  },
  "reason": "one line explanation"
}
 
Field names must be from this list ONLY:
incident_type, what_happened, parties.user_role, parties.opposing_party,
relief_sought, timeline, jurisdiction, evidence_available,
prior_legal_action, specific_sections_mentioned
 
If edit_type is "new_info", fields_affected and corrected_values can be empty.
If edit_type is "contradiction", corrected_values can be empty — just flag the fields.
"""

 
def _build_prompt(raw_query: str, case_log: CaseLog) -> str:
    return (
        f"Current case log:\n{case_log.to_context_string()}\n\n"
        f"User's latest message: {raw_query}\n\n"
        f"Is this a correction, new info, or contradiction?"
    )


def _apply_correction(case_log: CaseLog, corrected_values: dict) -> tuple[CaseLog, list[str]]:
    """
    Patches the case log with corrected values.
    Returns the updated log and a list of field names that were changed.
 
    Handles nested fields like parties.user_role cleanly.
    """

    patched_fields = []

    #model dump converts an object into a dict recursively. It does a deep convert to dict for any objects present inside the
    #parent obj
    log_dict = case_log.model_dump()

    for field, value in corrected_values.items():

        if "." in field:
            #extract the parent and child component from the corrected_values dict generated by the llm
            parent, child = field.split(".", 1)

            #if the parent field is a dict in the log_dict i.e. if its an object that contains attributes..
            if parent in log_dict and isinstance(log_dict[parent], dict):
                
                #correct the value on the case_log
                log_dict[parent][child] = value
                #make a note of the fields that get corrected
                patched_fields.append(field)
        else:
            if field in log_dict:
                log_dict[field] = value
                #make a note of the fields that get corrected
                patched_fields.append(field)


    # Reconstruct nested CaseParties if it exists
    if log_dict.get("parties") and isinstance(log_dict["parties"], dict):
        try:
            #instantiating a new caseparties onbj with the updated entries
            log_dict["parties"] = CaseParties(**log_dict["parties"])
        except Exception:
            pass

    # Rebuild CaseLog from patched dict
    try:
        updated_log = CaseLog(**log_dict)
    except Exception as e:
        print(f"[EditDetector] Failed to rebuild CaseLog after patch: {e}")
        updated_log = case_log  # safe fallback - keep original
 
    return updated_log, patched_fields


def detect_edit_node(state: GraphState) -> dict:

    """
    LangGraph node: detects if the user message is correcting the case log.
 
    Reads : state["raw_query"], state["case_log"]
    Writes: state["edit_detected"], state["edited_fields"],
            state["case_log"]  (patched if correction),
            state["answer"]    (set if contradiction needs user confirmation)
    """

    raw_query = state.get("raw_query", "")
    case_log  = state.get("case_log")
    awaiting_contradiction_resolution = state.get("awaiting_contradiction_resolution", False)


    # No log yet - nothing to correct, pass straight through
    if case_log is None or case_log.model_dump() == CaseLog().model_dump():
        print("[EditDetector] No existing case log — skipping edit detection.")
        return {
            "edit_detected": False,
            "edited_fields": [],
            "awaiting_contradiction_resolution" : False
        }
    
    #Flagged as contradiction from the previous turn
    if awaiting_contradiction_resolution:
        print(f"[EditDetector] Forced correction mode — resolving contradiction: '{raw_query[:80]}'")
 
        llm = ChatGroq(
            model       = "llama-3.3-70b-versatile",
            temperature = 0.0,
            max_tokens  = 300,
            api_key     = os.environ.get("GROQ_API_KEY"),
        )
 
        # Reuse the extractor prompt to pull the confirmed value as a correction
        forced_prompt = (
            f"The user was asked to clarify a contradiction in their case log.\n"
            f"Their confirmed answer is: '{raw_query}'\n\n"
            f"Current case log:\n{case_log.to_context_string()}\n\n"
            f"Extract which field(s) this confirms and their correct values.\n"
            f"Respond in the same JSON format as a correction."
        )
 
        messages = [
            SystemMessage(content=_SYSTEM_PROMPT),
            HumanMessage(content=forced_prompt),
        ]
 
        try:
            response         = llm.invoke(messages)
            raw_text         = response.content.strip()
            if raw_text.startswith("```"):
                parts    = raw_text.split("```")
                raw_text = parts[1]
                if raw_text.lower().startswith("json"):
                    raw_text = raw_text[4:]
            parsed           = json.loads(raw_text.strip())
            corrected_values = parsed.get("corrected_values", {})
 
            if corrected_values:
                updated_log, patched_fields = _apply_correction(case_log, corrected_values)
                changes = "\n".join(
                    f"  • **{f}** → {corrected_values.get(f, corrected_values.get(f.split('.')[-1], ''))}"
                    for f in patched_fields
                )
                answer = f"Got it, I've updated your case log:\n{changes}\n\nAnything else to correct or add?"
                print(f"[EditDetector] Contradiction resolved — patched: {patched_fields}")
                return {
                    "edit_detected":                    True,
                    "edited_fields":                    patched_fields,
                    "case_log":                         updated_log,
                    "answer":                           answer,
                    "awaiting_contradiction_resolution": False,  # ← reset flag
                }
        except Exception as e:
            print(f"[EditDetector] Forced correction parse error: {e} — passing through")
 
        # If extraction fails, reset flag and pass through to intake agent
        return {
            "edit_detected":                    False,
            "edited_fields":                    [],
            "awaiting_contradiction_resolution": False,
        }
    
    print(f"\n[EditDetector] Checking: '{raw_query[:80]}'")


    llm = ChatGroq(
        model       = "llama-3.3-70b-versatile",
        temperature = 0.0,
        max_tokens  = 300,
        api_key     = os.environ.get("GROQ_API_KEY"),
    )

    messages = [SystemMessage(_SYSTEM_PROMPT), HumanMessage(_build_prompt(raw_query=raw_query, case_log=case_log))]


    try:
        response = llm.invoke(messages)
        raw_text = response.content.strip()
 
        # Strip markdown fences if present
        if raw_text.startswith("```"):
            parts    = raw_text.split("```")
            raw_text = parts[1]
            if raw_text.lower().startswith("json"):
                raw_text = raw_text[4:]
        raw_text = raw_text.strip()
 
        parsed = json.loads(raw_text)
 
    except Exception as e:
        print(f"[EditDetector] Parse error: {e} — treating as new info")
        return {
            "edit_detected": False,
            "edited_fields": [],
            "awaiting_contradiction_resolution" : False
        }

    edit_type        = parsed.get("edit_type", "new_info")
    fields_affected  = parsed.get("fields_affected", [])
    corrected_values = parsed.get("corrected_values", {})
    reason           = parsed.get("reason", "")
 
    print(f"[EditDetector] → {edit_type} | fields: {fields_affected} | {reason}")


    #If parsing fails or no edits detected(contradiction or correction), pass through to Intake agent.
    if edit_type == "new_info":
        return {
            "edit_detected": False,
            "edited_fields": [],
            "awaiting_contradiction_resolution" : False
        }
    
    #Ask user for confirmation when the edit_type is contradiction
    if edit_type == "contradiction":
        conflict_fields = ", ".join(fields_affected)

        #NOTE: We are sending the below as our answer...
        answer = (
            f"I noticed a possible conflict in what you've told me about: **{conflict_fields}**. "
            f"Could you clarify which version is correct so I can update your case log accurately?"
        )
        print(f"[EditDetector] Contradiction detected in fields: {fields_affected}")

        #Updating "answer" in the graph state to stream...
        return {
            "edit_detected": True,
            "edited_fields": [],
            "answer":        answer,
            "awaiting_contradiction_resolution" : True
        }
    
    #If edit_type is correction and we have corrected values in the llm generated list...
    if edit_type == "correction" and corrected_values:

        updated_log, patched_fields = _apply_correction(case_log=case_log, corrected_values=corrected_values)
        
        print(f"[EditDetector] Patched fields: {patched_fields}")
       
        changes = "\n".join(
            f"  • **{f}** → {corrected_values.get(f, corrected_values.get(f.split('.')[-1], ''))}"
            for f in patched_fields
        )
        answer = f"Got it, I've updated your case log:\n{changes}\n\nAnything else to correct or add?"

        return {
            "edit_detected": True,
            "edited_fields": patched_fields,
            "case_log":      updated_log,
            "answer":        answer,
            "awaiting_contradiction_resolution" : False
        }
    
    #Fallback as new_info
    return {
        "edit_detected": False,
        "edited_fields": [],
        "awaiting_contradiction_resolution" : False
    }
